# Google Cloud Build Configuration for Markdown Editor
# Builds Docker image and deploys to Cloud Run

steps:
  # Step 1: Build the application
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        npm ci --silent
        echo "Building application..."
        npx vite build
        echo "Build completed successfully"
    dir: '.'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/markdown-editor:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/markdown-editor:latest'
      - '.'
    dir: '.'

  # Step 3: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/markdown-editor:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/markdown-editor:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'markdown-editor'
      - '--image=gcr.io/$PROJECT_ID/markdown-editor:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--concurrency=100'
      - '--timeout=300'
      - '--set-env-vars=NODE_ENV=production'
      - '--labels=app=markdown-editor,environment=production'

  # Step 5: Configure custom domain (optional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ -n "$_CUSTOM_DOMAIN" ]; then
          echo "Configuring custom domain: $_CUSTOM_DOMAIN"
          gcloud run domain-mappings create \
            --service=markdown-editor \
            --domain=$_CUSTOM_DOMAIN \
            --region=$_REGION \
            --platform=managed
        else
          echo "No custom domain specified, skipping domain mapping"
        fi

# Build configuration
options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _CUSTOM_DOMAIN: ''  # Set this to your domain (e.g., 'markdown.example.com')

# Build timeout
timeout: '1200s'

# Images to store in Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/markdown-editor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/markdown-editor:latest'

# Build tags for organization
tags:
  - 'markdown-editor'
  - 'production'